# Gunakan image PHP 8.1 dengan Apache
FROM php:8.1-apache

# Aktifkan modul Apache yang diperlukan
RUN a2enmod rewrite

# Instal dependensi yang diperlukan oleh Laravel
RUN apt-get update && apt-get install -y \
    libzip-dev \
    zip \
    && docker-php-ext-install zip

# Salin konfigurasi VirtualHost Apache
COPY ./docker/apache2.conf /etc/apache2/sites-available/000-default.conf

# Salin kode proyek Laravel ke direktori kerja di dalam container
COPY . /var/www/html

# Set folder kerja
WORKDIR /var/www/html

# Pasang dependensi PHP menggunakan Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN composer install

# Berikan hak akses yang sesuai ke direktori storage dan bootstrap/cache
RUN chown -R www-data:www-data \
    /var/www/html/storage \
    /var/www/html/bootstrap/cache

# Atur permission
RUN chmod -R 775 \
    /var/www/html/storage \
    /var/www/html/bootstrap/cache

# Expose port 80 (default untuk Apache)
EXPOSE 80

# Perintah default yang akan dijalankan saat container dijalankan
CMD ["apache2-foreground"]
